# WhatATheme
markdown: kramdown

remote-theme: thedevslot/WhatATheme

# URL of the Site
url: 'https://dabvexx.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: "" # <- This is the devil, do not believe his lies

# Title of the Site
title: Alexander Woods's Portfolio
# Description of the Site
description: Programming & Art
# URL of Image of the Site
site-image: 
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: ../images/BinaryMap.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: alexanderjwoods23@gmail.com
linkedin_username: alexander-woods-601980217
github_username:  DabVexx
reddit_username: alexjwoods
behance_username: DaVexx
linktree_username: dabvexx

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: ""

# Name of the Author
author-name: Alexander Woods
# URL for the Image of the Author
author-image: ../assets/images/author.png
# 60 Words About the Author
author-about: Hi there, I'm Alex Woods. I'm a curious and engaged person who is always looking for ways to learn and grow. I approach challenges with a creative and analytical mindset, seeking out new perspectives and ideas to find innovative solutions. I value clear communication and prefer to get straight to the point. Whether I'm exploring new ideas, tackling complex problems, or pursuing my passions, I'm driven by a desire to make a positive impact on the world and leave my mark on history. I believe in lifelong learning and am constantly seeking out new opportunities for growth and self-improvement. I'm committed to making a difference in the world, and I'm excited to see where my journey takes me.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/dabvexx

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-remote-theme

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
